// src/app/tools/roi-calculator/page.tsx
'use client';

import { useState } from 'react';
import { Calculator, Download, TrendingUp } from 'lucide-react';
import jsPDF from 'jspdf';

export default function ROICalculatorPage() {
  const [currentAnnualCost, setCurrentAnnualCost] = useState<number>(0);
  const [hoursPerWeek, setHoursPerWeek] = useState<number>(0);
  const [hourlyRate, setHourlyRate] = useState<number>(50);
  const [errorRate, setErrorRate] = useState<number>(5);
  const [automationCost, setAutomationCost] = useState<number>(0);
  const [expectedTimeSaving, setExpectedTimeSaving] = useState<number>(60);
  const [expectedErrorReduction, setExpectedErrorReduction] = useState<number>(80);

  const calculateCurrentAnnualCost = () => {
    return hoursPerWeek * 52 * hourlyRate;
  };

  const calculateErrorCost = () => {
    const avgErrorCost = 200; // Conservative estimate per error
    const errorsPerYear = (hoursPerWeek * 52) * (errorRate / 100);
    return errorsPerYear * avgErrorCost;
  };

  const calculateTotalCurrentCost = () => {
    return calculateCurrentAnnualCost() + calculateErrorCost();
  };

  const calculateAutomatedAnnualCost = () => {
    const reducedHours = hoursPerWeek * (1 - expectedTimeSaving / 100);
    return reducedHours * 52 * hourlyRate;
  };

  const calculateAutomatedErrorCost = () => {
    const currentErrorCost = calculateErrorCost();
    return currentErrorCost * (1 - expectedErrorReduction / 100);
  };

  const calculateTotalAutomatedCost = () => {
    return calculateAutomatedAnnualCost() + calculateAutomatedErrorCost() + automationCost;
  };

  const calculateAnnualSavings = () => {
    return calculateTotalCurrentCost() - calculateTotalAutomatedCost();
  };

  const calculatePaybackMonths = () => {
    const monthlySavings = calculateAnnualSavings() / 12;
    if (monthlySavings <= 0) return 999;
    return automationCost / monthlySavings;
  };

  const calculateROI = (years: number) => {
    const totalSavings = calculateAnnualSavings() * years;
    const totalInvestment = automationCost;
    if (totalInvestment === 0) return 0;
    return ((totalSavings - totalInvestment) / totalInvestment) * 100;
  };

  const generatePDF = () => {
    const doc = new jsPDF();
    
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.text('Automation ROI Analysis Report', 105, 20, { align: 'center' });
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Generated on ${new Date().toLocaleDateString('en-AU')}`, 105, 28, { align: 'center' });
    
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Current State', 20, 45);
    
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.text(`Manual Labor Cost: $${calculateCurrentAnnualCost().toLocaleString()}/year`, 20, 55);
    doc.text(`Error-Related Costs: $${calculateErrorCost().toLocaleString()}/year`, 20, 62);
    doc.text(`Total Annual Cost: $${calculateTotalCurrentCost().toLocaleString()}`, 20, 69);
    
    doc.setFont('helvetica', 'bold');
    doc.text('After Automation', 20, 85);
    
    doc.setFont('helvetica', 'normal');
    doc.text(`Reduced Labor Cost: $${calculateAutomatedAnnualCost().toLocaleString()}/year`, 20, 95);
    doc.text(`Reduced Error Cost: $${calculateAutomatedErrorCost().toLocaleString()}/year`, 20, 102);
    doc.text(`Automation Investment: $${automationCost.toLocaleString()}/year`, 20, 109);
    doc.text(`Total Annual Cost: $${calculateTotalAutomatedCost().toLocaleString()}`, 20, 116);
    
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.text('ROI Summary', 20, 135);
    
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.text(`Annual Savings: $${calculateAnnualSavings().toLocaleString()}`, 20, 145);
    doc.text(`Payback Period: ${calculatePaybackMonths().toFixed(1)} months`, 20, 152);
    doc.text(`1-Year ROI: ${calculateROI(1).toFixed(0)}%`, 20, 159);
    doc.text(`3-Year ROI: ${calculateROI(3).toFixed(0)}%`, 20, 166);
    doc.text(`5-Year ROI: ${calculateROI(5).toFixed(0)}%`, 20, 173);
    
    doc.setFontSize(9);
    doc.setTextColor(128, 128, 128);
    doc.text('Generated by NextWave.au | Enterprise Automation Solutions', 105, 285, { align: 'center' });
    
    doc.save('automation-roi-analysis.pdf');
  };

  const annualSavings = calculateAnnualSavings();
  const paybackMonths = calculatePaybackMonths();

  return (
    <div className="min-h-screen bg-black text-white">
      <div className="pt-32 pb-20 px-4">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-12">
            <h1 className="text-5xl font-semibold text-white mb-4 tracking-tight">Automation ROI Calculator</h1>
            <p className="text-lg text-white/60">Calculate the financial impact of business automation and prove ROI to stakeholders</p>
          </div>

          <div className="grid lg:grid-cols-2 gap-8">
            {/* Input Section */}
            <div className="bg-zinc-900 rounded-2xl p-8 space-y-6">
              <h2 className="text-2xl font-semibold mb-6">Current Situation</h2>
              
              <div>
                <label className="block text-sm font-semibold mb-2">Hours spent on manual tasks per week</label>
                <input
                  type="number"
                  value={hoursPerWeek || ''}
                  onChange={(e) => setHoursPerWeek(parseFloat(e.target.value) || 0)}
                  className="w-full bg-zinc-800 border border-white/10 rounded-lg p-3 text-white focus:ring-2 focus:ring-blue-500 focus:outline-none"
                  placeholder="e.g., 20"
                />
              </div>

              <div>
                <label className="block text-sm font-semibold mb-2">Average hourly rate ($/hour)</label>
                <input
                  type="number"
                  value={hourlyRate || ''}
                  onChange={(e) => setHourlyRate(parseFloat(e.target.value) || 0)}
                  className="w-full bg-zinc-800 border border-white/10 rounded-lg p-3 text-white focus:ring-2 focus:ring-blue-500 focus:outline-none"
                  placeholder="e.g., 50"
                />
              </div>

              <div>
                <label className="block text-sm font-semibold mb-2">Current error rate (%)</label>
                <input
                  type="number"
                  value={errorRate || ''}
                  onChange={(e) => setErrorRate(parseFloat(e.target.value) || 0)}
                  className="w-full bg-zinc-800 border border-white/10 rounded-lg p-3 text-white focus:ring-2 focus:ring-blue-500 focus:outline-none"
                  placeholder="e.g., 5"
                />
                <p className="text-xs text-white/50 mt-1">Manual processes typically have 3-10% error rates</p>
              </div>

              <h2 className="text-2xl font-semibold mb-6 pt-6 border-t border-white/10">Automation Plan</h2>

              <div>
                <label className="block text-sm font-semibold mb-2">Annual automation cost ($)</label>
                <input
                  type="number"
                  value={automationCost || ''}
                  onChange={(e) => setAutomationCost(parseFloat(e.target.value) || 0)}
                  className="w-full bg-zinc-800 border border-white/10 rounded-lg p-3 text-white focus:ring-2 focus:ring-blue-500 focus:outline-none"
                  placeholder="e.g., 12000"
                />
                <p className="text-xs text-white/50 mt-1">Include software, implementation, and training costs</p>
              </div>

              <div>
                <label className="block text-sm font-semibold mb-2">Expected time savings (%)</label>
                <input
                  type="number"
                  value={expectedTimeSaving || ''}
                  onChange={(e) => setExpectedTimeSaving(parseFloat(e.target.value) || 0)}
                  className="w-full bg-zinc-800 border border-white/10 rounded-lg p-3 text-white focus:ring-2 focus:ring-blue-500 focus:outline-none"
                  placeholder="e.g., 60"
                />
                <p className="text-xs text-white/50 mt-1">Industry average: 40-70% for document automation</p>
              </div>

              <div>
                <label className="block text-sm font-semibold mb-2">Expected error reduction (%)</label>
                <input
                  type="number"
                  value={expectedErrorReduction || ''}
                  onChange={(e) => setExpectedErrorReduction(parseFloat(e.target.value) || 0)}
                  className="w-full bg-zinc-800 border border-white/10 rounded-lg p-3 text-white focus:ring-2 focus:ring-blue-500 focus:outline-none"
                  placeholder="e.g., 80"
                />
                <p className="text-xs text-white/50 mt-1">Automation typically reduces errors by 70-95%</p>
              </div>
            </div>

            {/* Results Section */}
            <div className="space-y-6">
              <div className="bg-gradient-to-br from-blue-600 to-blue-800 rounded-2xl p-8">
                <div className="flex items-center gap-3 mb-4">
                  <TrendingUp className="w-8 h-8" />
                  <h2 className="text-2xl font-bold">Annual Savings</h2>
                </div>
                <p className="text-5xl font-bold mb-2">${annualSavings.toLocaleString()}</p>
                <p className="text-blue-200">Per year after automation</p>
              </div>

              <div className="bg-zinc-900 rounded-2xl p-6 space-y-4">
                <h3 className="text-xl font-semibold mb-4">Key Metrics</h3>
                
                <div className="flex justify-between items-center py-3 border-b border-white/10">
                  <span className="text-white/70">Payback Period</span>
                  <span className="text-xl font-bold">
                    {paybackMonths < 999 ? `${paybackMonths.toFixed(1)} months` : 'N/A'}
                  </span>
                </div>

                <div className="flex justify-between items-center py-3 border-b border-white/10">
                  <span className="text-white/70">1 Year ROI</span>
                  <span className="text-xl font-bold text-green-400">{calculateROI(1).toFixed(0)}%</span>
                </div>

                <div className="flex justify-between items-center py-3 border-b border-white/10">
                  <span className="text-white/70">3 Year ROI</span>
                  <span className="text-xl font-bold text-green-400">{calculateROI(3).toFixed(0)}%</span>
                </div>

                <div className="flex justify-between items-center py-3">
                  <span className="text-white/70">5 Year ROI</span>
                  <span className="text-xl font-bold text-green-400">{calculateROI(5).toFixed(0)}%</span>
                </div>
              </div>

              <div className="bg-zinc-900 rounded-2xl p-6">
                <h3 className="text-xl font-semibold mb-4">Cost Breakdown</h3>
                
                <div className="space-y-3">
                  <div>
                    <div className="flex justify-between text-sm mb-1">
                      <span className="text-white/70">Current Annual Cost</span>
                      <span className="font-semibold">${calculateTotalCurrentCost().toLocaleString()}</span>
                    </div>
                    <div className="w-full bg-zinc-800 rounded-full h-2">
                      <div className="bg-red-500 h-2 rounded-full" style={{ width: '100%' }}></div>
                    </div>
                  </div>

                  <div>
                    <div className="flex justify-between text-sm mb-1">
                      <span className="text-white/70">Automated Annual Cost</span>
                      <span className="font-semibold">${calculateTotalAutomatedCost().toLocaleString()}</span>
                    </div>
                    <div className="w-full bg-zinc-800 rounded-full h-2">
                      <div 
                        className="bg-green-500 h-2 rounded-full" 
                        style={{ width: `${(calculateTotalAutomatedCost() / calculateTotalCurrentCost()) * 100}%` }}
                      ></div>
                    </div>
                  </div>
                </div>
              </div>

              <button
                onClick={generatePDF}
                className="w-full bg-blue-600 text-white font-semibold px-6 py-4 rounded-lg hover:bg-blue-700 transition flex items-center justify-center gap-2"
              >
                <Download className="w-5 h-5" /> Download Full Report (PDF)
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
